package com.guardian.child

import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel
import android.app.AppOpsManager
import android.app.usage.UsageStatsManager
import android.content.Context
import android.content.Intent
import android.media.AudioAttributes
import android.media.MediaPlayer
import android.media.RingtoneManager
import android.os.Build
import android.os.Handler
import android.os.Looper
import android.os.Process
import android.provider.CallLog
import android.provider.Telephony
import android.provider.Settings
import android.database.Cursor
import android.Manifest
import android.content.pm.PackageManager
import androidx.core.content.ContextCompat
import java.util.Calendar

class MainActivity : FlutterActivity() {
        private val CHANNEL = "com.guardian.child/monitor"
        private var sirenPlayer: MediaPlayer? = null

        override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
                    super.configureFlutterEngine(flutterEngine)

                            MethodChannel(flutterEngine.dartExecutor.binaryMessenger, CHANNEL)
                                        .setMethodCallHandler { call, result ->
                                                            when (call.method) {
                                                                                    "startForegroundService" -> {
                                                                                                                try {
                                                                                                                                                val intent = Intent(this, MonitorService::class.java)
                                                                                                                                                                            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                                                                                                                                                                                                                startForegroundService(intent)
                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                startService(intent)
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                        result.success(true)
                                                                                                                                                                                                                                } catch (e: Exception) {
                                                                                                                                                result.error("SERVICE_ERROR", e.message, null)
                                                                                                                }
                                                                                    }
                                                                                                        "stopForegroundService" -> {
                                                                                                                                    stopService(Intent(this, MonitorService::class.java))
                                                                                                                                                            result.success(true)
                                                                                                        }
                                                                                                                            "hasUsageStatsPermission" -> {
                                                                                                                                                        val appOps = getSystemService(Context.APP_OPS_SERVICE) as AppOpsManager
                                                                                                                                                        val mode = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
                                                                                                                                                                                        appOps.unsafeCheckOpNoThrow(
                                                                                                                                                                                                                            AppOpsManager.OPSTR_GET_USAGE_STATS,
                                                                                                                                                                                                                            Process.myUid(),
                                                                                                                                                                                                                            packageName
                                                                                                                                                                                                                        )
                                                                                                                                                                                                                } else {
                                                                                                                                                                                        @Suppress("DEPRECATION")
                                                                                                                                                                                                                    appOps.checkOpNoThrow(
                                                                                                                                                                                                                                                        AppOpsManager.OPSTR_GET_USAGE_STATS,
                                                                                                                                                                                                                                                        Process.myUid(),
                                                                                                                                                                                                                                                        packageName
                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                            }
                                                                                                                                                                                result.success(mode == AppOpsManager.MODE_ALLOWED)
                                                                                                                            }
                                                                                                                                                "openUsageAccessSettings" -> {
                                                                                                                                                                            startActivity(Intent(Settings.ACTION_USAGE_ACCESS_SETTINGS))
                                                                                                                                                                                                    result.success(true)
                                                                                                                                                                                                                        }
                                                                                                                                                                    "getAppUsage" -> {
                                                                                                                                                                                                try {
                                                                                                                                                                                                                                val usm = getSystemService(Context.USAGE_STATS_SERVICE) as UsageStatsManager
                                                                                                                                                                                                                                val cal = Calendar.getInstance()
                                                                                                                                                                                                                                                            val endTime = cal.timeInMillis
                                                                                                                                                                                                                                cal.set(Calendar.HOUR_OF_DAY, 0)
                                                                                                                                                                                                                                                            cal.set(Calendar.MINUTE, 0)
                                                                                                                                                                                                                                                                                        cal.set(Calendar.SECOND, 0)
                                                                                                                                                                                                                                                                                                                    val startTime = cal.timeInMillis
                                                                                                                                                                                                    
                                                                                                                                                                                                                                val stats = usm.queryUsageStats(
                                                                                                                                                                                                                                                                    UsageStatsManager.INTERVAL_DAILY, startTime, endTime
                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                            val map = HashMap<String, Long>()
                                                                                                                                                                                                                                                                                        stats?.forEach { s ->
                                                                                                                                                                                                                                                                                                                            if (s.totalTimeInForeground > 60000) {
                                                                                                                                                                                                                                                                                                                                                                    map[s.packageName] = s.totalTimeInForeground / 60000
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                    result.success(map)
                                                                                                                                                                                                                                                                                                                                            } catch (e: Exception) {
                                                                                                                                                                                                                                result.error("USAGE_ERROR", e.message, null)
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                    }
                                                                                                                                                                                        "getCallLog" -> {
                                                                                                                                                                                                                    try {
                                                                                                                                                                                                                                                    if (ContextCompat.checkSelfPermission(this, Manifest.permission.READ_CALL_LOG)
                                                                                                                                                                                                                                                                                    != PackageManager.PERMISSION_GRANTED) {
                                                                                                                                                                                                                                                                                        result.success(emptyList<Map<String, Any>>())
                                                                                                                                                                                                                                                                                                                        return@setMethodCallHandler
                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                val calls = mutableListOf<Map<String, Any>>()
                                                                                                                                                                                                                                                                                                            val cal = Calendar.getInstance()
                                                                                                                                                                                                                                                                                                                                        cal.add(Calendar.DAY_OF_YEAR, -7)
                                                                                                                                                                                                                                                                                                                                                                    val since = cal.timeInMillis.toString()
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                val cursor: Cursor? = contentResolver.query(
                                                                                                                                                                                                                                                                                                                                                                                                                                    CallLog.Calls.CONTENT_URI,
                                                                                                                                                                                                                                                                                                                                                                                                                                    arrayOf(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CallLog.Calls.NUMBER,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CallLog.Calls.CACHED_NAME,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CallLog.Calls.TYPE,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CallLog.Calls.DATE,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            CallLog.Calls.DURATION
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ),
                                                                                                                                                                                                                                                                                                                                                                                                                                    "${CallLog.Calls.DATE} > ?",
                                                                                                                                                                                                                                                                                                                                                                                                                                    arrayOf(since),
                                                                                                                                                                                                                                                                                                                                                                                                                                    "${CallLog.Calls.DATE} DESC"
                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                            cursor?.use { c ->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                while (c.moveToNext() && calls.size < 50) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        val typeInt = c.getInt(c.getColumnIndexOrThrow(CallLog.Calls.TYPE))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            val typeStr = when (typeInt) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        CallLog.Calls.INCOMING_TYPE -> "incoming"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        CallLog.Calls.OUTGOING_TYPE -> "outgoing"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        CallLog.Calls.MISSED_TYPE -> "missed"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        CallLog.Calls.REJECTED_TYPE -> "rejected"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        else -> "unknown"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                calls.add(mapOf(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "number" to (c.getString(c.getColumnIndexOrThrow(CallLog.Calls.NUMBER)) ?: ""),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "name" to (c.getString(c.getColumnIndexOrThrow(CallLog.Calls.CACHED_NAME)) ?: ""),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "type" to typeStr,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "date" to c.getLong(c.getColumnIndexOrThrow(CallLog.Calls.DATE)),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "duration" to c.getLong(c.getColumnIndexOrThrow(CallLog.Calls.DURATION))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        result.success(calls)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (e: Exception) {
                                                                                                                                                                                                                                                    result.error("CALL_LOG_ERROR", e.message, null)
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                            "getSmsLog" -> {
                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                        if (ContextCompat.checkSelfPermission(this, Manifest.permission.READ_SMS)
                                                                                                                                                                                                                                                                                                        != PackageManager.PERMISSION_GRANTED) {
                                                                                                                                                                                                                                                                                                            result.success(emptyList<Map<String, Any>>())
                                                                                                                                                                                                                                                                                                                                            return@setMethodCallHandler
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                    val messages = mutableListOf<Map<String, Any>>()
                                                                                                                                                                                                                                                                                                                                val cal = Calendar.getInstance()
                                                                                                                                                                                                                                                                                                                                                            cal.add(Calendar.DAY_OF_YEAR, -7)
                                                                                                                                                                                                                                                                                                                                                                                        val since = cal.timeInMillis.toString()
                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                    val cursor: Cursor? = contentResolver.query(
                                                                                                                                                                                                                                                                                                                                                                                                                                                        Telephony.Sms.CONTENT_URI,
                                                                                                                                                                                                                                                                                                                                                                                                                                                        arrayOf(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Telephony.Sms.ADDRESS,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Telephony.Sms.BODY,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Telephony.Sms.TYPE,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Telephony.Sms.DATE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ),
                                                                                                                                                                                                                                                                                                                                                                                                                                                        "${Telephony.Sms.DATE} > ?",
                                                                                                                                                                                                                                                                                                                                                                                                                                                        arrayOf(since),
                                                                                                                                                                                                                                                                                                                                                                                                                                                        "${Telephony.Sms.DATE} DESC"
                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                cursor?.use { c ->
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    while (c.moveToNext() && messages.size < 50) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            val typeInt = c.getInt(c.getColumnIndexOrThrow(Telephony.Sms.TYPE))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                val typeStr = when (typeInt) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Telephony.Sms.MESSAGE_TYPE_INBOX -> "received"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Telephony.Sms.MESSAGE_TYPE_SENT -> "sent"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else -> "other"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    messages.add(mapOf(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "address" to (c.getString(c.getColumnIndexOrThrow(Telephony.Sms.ADDRESS)) ?: ""),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "body" to (c.getString(c.getColumnIndexOrThrow(Telephony.Sms.BODY)) ?: ""),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "type" to typeStr,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "date" to c.getLong(c.getColumnIndexOrThrow(Telephony.Sms.DATE))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            result.success(messages)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } catch (e: Exception) {
                                                                                                                                                                                                                                                                        result.error("SMS_LOG_ERROR", e.message, null)
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                "getBrowserHistory" -> {
                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                            result.success(BrowserMonitorService.urlHistory.map { entry ->
                                                                                                                                                                                                                                                                                                                                mapOf(
                                                                                                                                                                                                                                                                                                                                                                        "url" to (entry["url"] as? String ?: ""),
                                                                                                                                                                                                                                                                                                                                                                        "packageName" to (entry["packageName"] as? String ?: ""),
                                                                                                                                                                                                                                                                                                                                                                        "timestamp" to (entry["timestamp"] as? Long ?: 0L)
                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                            })
                                                                                                                                                                                                                                                                                                                    } catch (e: Exception) {
                                                                                                                                                                                                                                                                                            result.error("BROWSER_ERROR", e.message, null)
                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                    "hasAccessibilityPermission" -> {
                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                val enabledServices = Settings.Secure.getString(
                                                                                                                                                                                                                                                                                                                                                    contentResolver,
                                                                                                                                                                                                                                                                                                                                                    Settings.Secure.ENABLED_ACCESSIBILITY_SERVICES
                                                                                                                                                                                                                                                                                                                                                ) ?: ""
                                                                                                                                                                                                                                                                                                                result.success(enabledServices.contains(packageName))
                                                                                                                                                                                                                                                                                                                                        } catch (e: Exception) {
                                                                                                                                                                                                                                                                                                                result.success(false)
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                        "openAccessibilitySettings" -> {
                                                                                                                                                                                                                                                                                                    startActivity(Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS))
                                                                                                                                                                                                                                                                                                                            result.success(true)
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                            "playSiren" -> {
                                                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                                                                                        sirenPlayer?.release()
                                                                                                                                                                                                                                                                                                                                                                                    val uri = RingtoneManager.getDefaultUri(RingtoneManager.TYPE_ALARM)
                                                                                                                                                                                                                                                                                                                                                                                                                sirenPlayer = MediaPlayer().apply {
                                                                                                                                                                                                                                                                                                                                                                                                                                                    setDataSource(this@MainActivity, uri)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    setAudioAttributes(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            AudioAttributes.Builder()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .setUsage(AudioAttributes.USAGE_ALARM)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .setContentType(AudioAttributes.CONTENT_TYPE_SONIFICATION)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .build()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    isLooping = true
                                                                                                                                                                                                                                                                                                                                                                                                                                                    prepare()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    start()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                            Handler(Looper.getMainLooper()).postDelayed({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sirenPlayer?.release()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sirenPlayer = null
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }, 30000)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        result.success(true)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                } catch (e: Exception) {
                                                                                                                                                                                                                                                                                                                                                        result.error("SIREN_ERROR", e.message, null)
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                "stopSiren" -> {
                                                                                                                                                                                                                                                                                                                                            sirenPlayer?.release()
                                                                                                                                                                                                                                                                                                                                                                    sirenPlayer = null
                                                                                                                                                                                                                                                                                                                                            result.success(true)
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                    else -> result.notImplemented()
                                                                                                                                                                                                                                                                                                                                                    }
                                        }
        }
}
